# Generated by Django 5.0.6 on 2024-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlog', '0003_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Blog', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='No description', max_length=255),
        ),
    ]
